apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["30s"]
        resources:
          requests:
            cpu: 2
            memory: 1Gi
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job1
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue1
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["30s"]
        resources:
          requests:
            cpu: 2
      restartPolicy: Never