apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-2
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-2
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["30s"]
        resources:
          requests:
            cpu: 9
            memory: "200Mi"
      restartPolicy: Never
